# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'InTime' do
pod 'TwilioSDK', '~>1.2'
end

target 'InTimeTests' do

end

target 'InTimeUITests' do

end

